### ISSUE TITLE
Bättre lösning till bild-lagring

### ISSUE THREAD

**Issue by vgrenfors** [LuleaMakerspace/projekt.makerspace#2]
Just nu ligger bilderna lite överallt i cyber rymden, hur fixar vi det på ett okomplicerat sätt?

**Comment by ulve** [comment]
Skapa issues så hjälper jag till
fre 5 okt. 2018 kl. 16:40 skrev Victor Forsgren <notifications@github.com>:

**Comment by ulve** [comment]
jag kan fixa en s3 bucket att hosta dom från. det är näst intill gratis.

**Comment by vgrenfors** [comment]
"$0.023 per GB"
Riktigt billigt, sjukt najs om du hade kunnat fixa.

**Comment by ulve** [comment]
nu finns en bucket i vart fall. skall se hur vi gör uploaden sen

**Comment by vgrenfors** [comment]
# VERY GOOD

**Comment by ulve** [comment]
fast ja jag vet ju inte hur man löser det så enkelt som möjligt. man måste ju ha någon form av inloggning först och främst. sen måste man fixa ihop den med aws. kanske cognito kanske nått annat

**Comment by vgrenfors** [comment]
# Jag tror bara att du och jag behöver tillgång till bucketen
Med tanke på att jag använder mig av en *Google Form* och lägger in alla spel själv.

**Comment by vgrenfors** [comment]
hello mi friend

**Comment by vgrenfors** [comment]
lamp

**Comment by ulve** [comment]
jaha du vill inte att man skall ladda upp från sidan utan från lokalt. ja då är det lätt som en plätt. du måste bara ha en aws användare så kan jag ge rättigheter

**Comment by vgrenfors** [comment]
rättigheter till alla

**Comment by vgrenfors** [comment]
:)

**Comment by vgrenfors** [comment]
(Einar har tangentbordet)

**Comment by vgrenfors** [comment]
fake news
